### ISSUE TITLE
Script php artisan optimize handling the post-install-cmd event returned with an error

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/Demo#1]
When I install a demo I get an error.

```
Script php artisan optimize handling the post-install-cmd event returned with an error

[RuntimeException]
Error Output:
```

Anything I need to do?

**Comment by tabacitu** [comment]
Hi! Just tried it again and worked like a charm for me. Could you please post the error? What comes _after_ "error output"?

**Comment by poxin13** [comment]
Having the same issue here.

php artisan optimize
                         
  [Illuminate\Database\QueryException]                                                            
  SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error (SQL: SHOW TABLES LIKE '
  [PDOException]                                               
  SQLSTATE[HY000]: General error: 1 near "SHOW": syntax 
Script php artisan optimize handling the post-install-cmd event returned with an error

**Comment by poxin13** [comment]
Having the same issue here.


php artisan optimize

  [Illuminate\Database\QueryException]                                                            
  SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error (SQL: SHOW TABLES LIKE 'settings')  

  [PDOException]                                               
  SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error

Script php artisan optimize handling the post-install-cmd event returned with an error

**Comment by poxin13** [comment]
Fixed it, cant use sqlite - requires MySQL for the demo install.

**Comment by tabacitu** [comment]
Yes it does.... Right now only MySQL and PosgreSQL are supported (with a known minor issue in PosgreSQL), but SQLite and MongoDB support will be coming. It's just not a priority, so it will probably be a few months until then, sorry.

If, however, you'd like to contribute with that, I'd be more than happy to merge your pull requests.

**Comment by tabacitu** [comment]
Fixed! :-) PosgreSQL and SQLite should work fine.

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by OwenMelbz** [comment]
Ha i've actually encountered this..and its throwing a spanner in the works.

We use an automated deployment system that pulls in and deploys composer dependencies, which intern runs `php artisan optimize` on the CI. however because the CI does not have a database on there it fails.

It effectively means we cant automatically deploy if we're using the settings package without installing a dummy mysql db on the CI..

**Comment by shinokada** [comment]
I am trying to install it again, but I get this error now.

>...
>... 
> php artisan optimize
> 
>   [ErrorException]
>   Declaration of App\Providers\EventServiceProvider::boot() should be compatible with Illuminate\Foundation\Support\Providers\EventServiceProvider::boot()
> 
> Script php artisan optimize handling the post-update-cmd event returned with error code 1

**Comment by claytron5000** [comment]
Years later, I'm looking for the same solution, any update @OwenMelbz ?
