### ISSUE TITLE
[Bug] Upload multiple can't hold many items if it's VARCHAR

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/demo#103]
# Bug report

### What I did:

Tested the Monster's "upload_multiple" input with a few of files at one (3-6). Uploaded 1-2. Saved. Then uploaded 4-5. Saved.

### What I expected to happen:

They get saved / replaced.

### What happened:

The input got cleared entirely.

### What I've already tried to fix it:

After a few hours of looking at the JS and PHP, I realized it's a DB issue :-) The db column is VARCHAR so it can only hold 255 characters - I was trying to plug in a lot more. Changing it to TEXT fixed it for me, but it should also:
- [ ] be fixed in the main demo migration (to prevent user frustration)
- [x] be mentioned in the upload_multiple documentation

**Comment by promatik** [comment]
This one was fixed long time ago I believe in #290.
I'll close this one 🙌
