### ISSUE TITLE
404 * Page not found

### ISSUE THREAD

**Issue by BenJule** [Laravel-Backpack/Demo#12]
I have installed the Demo Panel with all Sites on my (sub.domain.tld), if i create a new Frontend page i get a Error 404 on the new Page :(

**Comment by tabacitu** [comment]
Hi @BenJule ,

Backpack does not provide the front-end for the web pages, only the backend. Please see [this issue](https://github.com/Laravel-Backpack/pagemanager/issues/2) for more details and an example of how you can code the front-end.

Cheers!
