### ISSUE TITLE
Cannot get demo up and running with MAMP

### ISSUE THREAD

**Issue by qommander** [Laravel-Backpack/Demo#13]
Using MAMP with composer.phar, laravel and backpack-demo inside htdocs. When I try to run composer install to backback-demo folder I get the following:

`
...
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                    
  [Doctrine\DBAL\Driver\PDOException]               
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

                                                    
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

Script php artisan optimize handling the post-update-cmd event returned with error code 1
`

Any ideas what I can do? I have attempted many times with different MySQL ports (i.e. 8889, 3306) and with different db hostnames (i.e. localhost, 127.0.0.1). MAMP PHP version set to 5.6.27 but active version is 5.6.33 and MAMP PHP cache setting is set to off. Here is my current .env file code:

`
APP_ENV=local
APP_DEBUG=true
APP_KEY=SomeRandomString
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

`
Anything else I can give you to help me solve? I really don't know if it's a problem with my environment or with Backpack. Backback is something I would definitely like to work with for an up and coming project and perhaps further into the future. Good job on it!! ;))

**Comment by tabacitu** [comment]
Hi @qommander ,

Before running ```composer install``` you should make sure the Laravel installation is up-and-running. Please don't forget to do step #2 in the [demo installation process](https://laravel-backpack.readme.io/docs/demo). It says:

```
2) Set your database information in your .env file (use the .env.example as an example);
```

I don't think your .env file is ok. If you're using MAMP, you should probably have something like this:
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=your_database_name_here
DB_USERNAME=root
DB_PASSWORD=root
```

Cheers!

**Comment by qommander** [comment]
Thank you tabacitu! I had some ports crossed but it's working now.. ;))
