### ISSUE TITLE
env file is missing

### ISSUE THREAD

**Issue by shrestha463** [Laravel-Backpack/Demo#14]
please fill up the changes in the .env file as,

APP_ENV=local
APP_DEBUG=true
APP_KEY=1CaND3OKKvOGSBAlCg6IyrRmTQWwZjOO

DB_HOST = localhost
DB_DATABASE = YOUR_DATABASE_NAME
DB_USERNAME = root
DB_PASSWORD = 

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null

NOTE: Only change the database name that you have created.

**Comment by OwenMelbz** [comment]
This is normal thing to do for a laravel project, you can even see there is a composer.json command that does this for you.

You'd also need to run `php artisan key:generate` to update it.

You can read more about how it works here -> https://laravel.com/docs/5.3/configuration#environment-configuration
