### ISSUE TITLE
installation fails on laravel 5.3

### ISSUE THREAD

**Issue by broszies** [Laravel-Backpack/Demo#15]
Hi,
my third attempt to install on an Laravel Homestead Vagrant VM failed today.
as to my knowledge Homestead is up to date, Laravel certainly is (ran composer update before install).
Same error happenes when I use git clone install after composer install

and when I follow https://laravel-backpack.readme.io/docs/installation-on-laravel-53

Any ideas?

-------------
Error log:
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be su                                 rrounded by quotes. in /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php:228
Stack trace:
#0 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(97): Dotenv\Loader->sanitiseVariab                                 leValue('DB_PASSWORD', '-----.')
#1 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(330): Dotenv\Loader->normaliseEnvi                                 ronmentVariable('DB_PASSWORD', ----')
#2 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(58): Dotenv\Loader->setEnvironment                                 Variable('DB_PASSWORD=----')
#3 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Dotenv.php(91): Dotenv\Loader->load()
#4 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Dotenv.php(48): Dotenv\Dotenv->loadData()
#5 /home/vagrant/web/backpack-demo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/DetectEnviro                                 nment.php(24): Dotenv\Dotenv->load()
#6 /home/vagrant/we in /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php on line 228

Fatal error: Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surroun                                 ded by quotes. in /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php:228
Stack trace:
#0 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(97): Dotenv\Loader->sanitiseVariab                                 leValue('DB_PASSWORD', '----')
#1 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(330): Dotenv\Loader->normaliseEnvi                                 ronmentVariable('DB_PASSWORD', '----')
#2 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(58): Dotenv\Loader->setEnvironment                                 Variable('DB_PASSWORD=----')
#3 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Dotenv.php(91): Dotenv\Loader->load()
#4 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Dotenv.php(48): Dotenv\Dotenv->loadData()
#5 /home/vagrant/web/backpack-demo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/DetectEnviro                                 nment.php(24): Dotenv\Dotenv->load()
#6 /home/vagrant/we in /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php on line 228
Script php artisan optimize handling the post-install-cmd event returned with error code 255

**Comment by broszies** [comment]
Tried to install base as per https://laravel-backpack.readme.io/docs/installation-on-laravel-53

result is the same:

-------------------
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surrounded by quotes. in /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php:228
Stack trace:
#0 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(97): Dotenv\Loader->sanitiseVariableValue('DB_PASSWORD', 'ich will hier r...')
#1 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(330): Dotenv\Loader->normaliseEnvironmentVariable('DB_PASSWORD', 'ich will hier r...')
#2 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(58): Dotenv\Loader->setEnvironmentVariable('DB_PASSWORD=ich...')
#3 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Dotenv.php(91): Dotenv\Loader->load()
#4 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Dotenv.php(48): Dotenv\Dotenv->loadData()
#5 /home/vagrant/web/backpack-demo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/DetectEnvironment.php(24): Dotenv\Dotenv->load()
#6 /home/vagrant/we in /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php on line 228

Fatal error: Uncaught Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surrounded by quotes. in /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php:228
Stack trace:
#0 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(97): Dotenv\Loader->sanitiseVariableValue('DB_PASSWORD', 'ich will hier r...')
#1 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(330): Dotenv\Loader->normaliseEnvironmentVariable('DB_PASSWORD', 'ich will hier r...')
#2 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php(58): Dotenv\Loader->setEnvironmentVariable('DB_PASSWORD=ich...')
#3 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Dotenv.php(91): Dotenv\Loader->load()
#4 /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Dotenv.php(48): Dotenv\Dotenv->loadData()
#5 /home/vagrant/web/backpack-demo/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/DetectEnvironment.php(24): Dotenv\Dotenv->load()
#6 /home/vagrant/we in /home/vagrant/web/backpack-demo/vendor/vlucas/phpdotenv/src/Loader.php on line 228
Script php artisan optimize handling the post-update-cmd event returned with error code 255

Installation failed, reverting ./composer.json to its original content.

**Comment by broszies** [comment]
Haha.
Issue solved.
The database password in the .env flie 8and thus for mysql may NOT contain spaces.
Fixed.

**Comment by OwenMelbz** [comment]
Ha yes, always read the error messages :p

Dotenv\Exception\InvalidFileException: Dotenv values containing spaces must be surrounded by quotes. in
