### ISSUE TITLE
pagemanager not working in 4.1

### ISSUE THREAD

**Issue by harrison-patel** [Laravel-Backpack/demo#166]
Error
Call to undefined function Backpack\PageManager\app\Http\Controllers\Admin\title_case()
http://localhost:8001/admin/page/create

**Comment by tabacitu** [comment]
Indeed, it had a PR but it wasn't published. Thank for opening the issue @harrison-patel . I think you'll be glad to know that a few minutes ago I've tagged and soft-launched Backpack 4.1. So it's out of beta.

You can now install the version `4.1.*`, and update the add-on versions to real versions. Check out [the upgrade guide](https://backpackforlaravel.com/docs/4.1/upgrade-guide#step-2), I've just tagged and updated the add-on versions too.

Let us know if you're still having the problem and we'll reopen.
Cheers!
