### ISSUE TITLE
Fresh demo Install gives Charts related Java Script errors

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/demo#168]
# Bug report
### What I did:
Fresh demo Install only

### JS ERROR:
![image](https://user-images.githubusercontent.com/8214221/81780575-5d92ae80-9514-11ea-9f02-c377ce3bf93f.png)

I'm unable to resolve unexpected json token, however the passed json in the demo is actually fine. I'm using Google Chrome.

**Comment by tabacitu** [comment]
How - weirdly enough, I get it too now, thanks @karandatwani92 ! What's odd is that for me it only happens if DebugBar is loaded onpage. So if I do `APP_DEBUG=false` in my .ENV file, this all goes away...

I'll come back to this after digging in more carefully - these JS conflicts are never easy to solve.
Thanks again @karandatwani92 .

**Comment by pxpm** [comment]
Hello @karandatwani92 and @tabacitu 

Sorry for the time to tackle on this one. 

Indeed one of the errors is a known one, that is the charts complaining that we are trying to load the library more than once, atm we don't have a final solution for it, but it should work with that error like in https://demo.backpackforlaravel.com/admin/dashboard

But I got also the second error that @karandatwani92 shows, that is related with malformed json in api response so both charts that depend on api response does not show.

I can confirm that this does not happen in online demo @tabacitu ? But it happens to me in a new instalation.

I'v just submited PR #189 that overrides the response method in controller to return valid json response for ajax charts.

Going to close this as we have a solution, any further discussion should be addressed in PR thread. 

Thanks again @karandatwani92 for the bug report.

Best,
Pedro
