### ISSUE TITLE
widget

### ISSUE THREAD

**Issue by bastha** [Laravel-Backpack/Demo#17]
hi ,i am looking for widget in dashboard, i dont know how to add 
thank you

**Comment by OwenMelbz** [comment]
Hi @bastha

As this is not related to the demo, could you please open a issue in the correct project please.

Thanks

https://github.com/Laravel-Backpack/Base

**Comment by tabacitu** [comment]
Also, you might find the answer here: https://github.com/Laravel-Backpack/Base/issues/37#issuecomment-247524639

Cheers!
