### ISSUE TITLE
Running backpack demo

### ISSUE THREAD

**Issue by jambari** [Laravel-Backpack/Demo#19]
I was running backpack demo according this guide [https://laravel-backpack.readme.io/docs/demo](url) , but when I was trying to open register page, it returned 404 , I read the Update PageManagerServiceProvider.php, and I am sure, the codes are same, how to fix this ?

**Comment by OwenMelbz** [comment]
Have you enabled registrations in the config?

**Comment by jambari** [comment]
In config/backpack/base.php 
'registration_open' => true,

**Comment by OwenMelbz** [comment]
If you run `php artisan route:list` do you get the registration url in it?

**Comment by jambari** [comment]
if I run php artisan route:list ,it returned like this

[2017-01-03 19:36:07] local.ERROR: ReflectionException: Class App\Http\Controllers\Auth\LoginController does not exist in /home/jambari/Desktop/backpack-demo/vendor/laravel/framework/src/Illuminate/Container/Container.php:749

**Comment by OwenMelbz** [comment]
There you go then! Looks like something is very wrong.

I'd recommend deleting the whole project and starting from scratch reading the documentation carefully as it looks like a step has been missed during the install

**Comment by jambari** [comment]
Would you mind if you give me a clue or  what step did I miss ?

**Comment by jambari** [comment]
Ok it's done ! I install it manually using backpack for laravel 5.3 install guide. Thank you for your help
