### ISSUE TITLE
User management module

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/demo#2]
Hi, I am wondering if you are creating a user management module as well.

**Comment by tabacitu** [comment]
Hi @shinokada ,

It's already done. Take a look at [Backpack/PermissionManager](https://github.com/Laravel-Backpack/permissionmanager).

Cheers!

**Comment by shinokada** [comment]
Thanks. I will try it. 
FYI: When I use composer, I get the following.

    Package prologue/alerts is abandoned, you should avoid using it. No replacement was suggested.

**Comment by tabacitu** [comment]
Hmm... Thanks, will consider switching in Backpack v3. Cheers!
