### ISSUE TITLE
More demo entities, to show off & test all Backpack features

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Demo#22]
Without unit tests, each Backpack change might break something, and it's very very difficult to see if it does.

I propose creating some new entities in the Demo, which would show off all Backpack features. This should be useful both for demonstration purposes AND for testing. The only downside I see is that people who use the Demo to kickstart their projects (_I know there are people, even though we explicitly said not to do that_) will have these extra entities in their new projects and need to delete them. **Does anybody see another reason this isn't a good idea?**

That being said, here's what I have in mind for these entities:
- Test (has all field types, all column types, seeds for ~10 entries)
- Product (seeds for ~1 million entries, ajax datatables, buttons, filters, details_row, revisions,  export buttons, fake fields, translatable fields)
- Comment (reordering and nesting, morphTo)

@OwenMelbz , what do you think? Aslo, did I miss any feature :-) ?

**Comment by OwenMelbz** [comment]
Seems a good idea yeah - I think we need to have maybe some example usage/limitations with the ajaxTable thing as theres lots of quirks with that.

I wonder if we approach this a little differently. Create a pre-bundled .zip which does not need composer etc.

Then within it it has some custom checks that basically break the site if its not used as expected, for example if we set in .env the `APP_ENV = demo` - we can then include some code which see's if demo is ever changed. if it is then cause a error.

Also pulling it out of composer means that people will not then be able to randomly add new packages and start using it, maybe even bin the artisan binary etc, this means that they can literally dump the downloaded file into a vhost setup - then view it in their browser. (maybe see if we can use mysqlite so we dont even need to worry about running migrations etc)

Then they can have a local development, but its pretty much dead to use outside of that?

Or even think again about the "online hosted demo" which people can play with, but not download use.

I guess it depends if yo want a true demo - or something in between?

**Comment by tabacitu** [comment]
@OwenMelbz  to be honest, not a big fan of the "downloading zip" solution, but I don't have a clear rational explanation for it. I guess it's because it will make backpack look like it's using old PHP technology, instead of following the current best practices (composer).

I do, however, tend to lean give more credit to your initial suggestion of "online hosted demo". Right now it seems like it would be the fastest way to test-drive the Backpack interface. So basically we'd be able to give the user 2 options to test:
- try the interface in the online demo (database is refreshed every hour)
- install the demo on you local machine and play around in the code

Sounds pretty good right now :-)
