### ISSUE TITLE
When saving a new Page

### ISSUE THREAD

**Issue by mgazelle** [Laravel-Backpack/Demo#24]
BadMethodCallException in Builder.php line 2450:
Call to undefined method Illuminate\Database\Query\Builder::getCastedAttributes()

**Comment by tabacitu** [comment]
Hi @mgazelle ,

Sounds like an issue that has been fixed in the meantime. Could you please tell me if a ```composer update``` fixes it for you?

Cheers!

**Comment by borislav-itskov** [comment]
Composer update fixes the issue :)

**Comment by oldskool73** [comment]
+1 also just got the same thing on a fresh install, `composer updated` fixes it, seems like all you need is an updated lock file in the repo to fix it.
