### ISSUE TITLE
Cannot run demo migrations in PostgreSQL

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/demo#242]
# Bug report

### What I did:

Tried to install the demo using PostgreSQL. Ran `php artisan migrate` and `php artisan db:seed`.

### What I expected to happen:

Migrations to run successfully.

### What happened:

Migrations did NOT run successfully because of the raw DB statement we have inside `create_monsters_table.php`:
![Screenshot 2021-02-24 at 09 13 39](https://user-images.githubusercontent.com/1032474/108961976-c51f8200-7680-11eb-90d9-956758ea62fe.png)

### What I've already tried to fix it:

Removed those two lines:
```php
        $prefix = DB::getTablePrefix();
        DB::statement("ALTER TABLE {$prefix}monsters MODIFY base64_image MEDIUMBLOB");
```

Everything's running smoothly afterwards. I'm thinking of reverting https://github.com/Laravel-Backpack/demo/pull/203, which introduced this. It is MUCH more important for the demo to be installable on PostgreSQL as-is, than it is to test changing the db prefix then re-running the migrations.

### Backpack, Laravel, PHP, DB version:
```bash
### PHP VERSION:
PHP 7.4.13 (cli) (built: Nov 30 2020 14:57:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.22.1@5c70991b96c5722afed541a996479b5112654c8b

### BACKPACK VERSION:
4.1.30@62856b1f01fc3e05c80140fc22f85ea2aac8368c
```

**Comment by tabacitu** [comment]
@promatik could you please take another look at this? I still don't quite understand why we need this when changing db prefix (any why only for the `base64_image` column). If we're to provide a fix for this, it should be using Laravel Migrations, not raw db statement, so that it works on all DB types.

**Comment by tabacitu** [comment]
Ah. I see @promatik 's PR was there only because of https://github.com/Laravel-Backpack/demo/commit/4587452d01455ba3c056871066afa9b8028f23aa#diff-c43a192e5eeef13d59a8b373f2d3eb65fbee5b4b5ed1aea86d17e622273fed4c - so the DB statement was there only to allow bigger images. 

Right now... I no longer agree with making the `base64_image` column bigger. Storing base64 images in the db is a bad idea anyway. Making the column even bigger is making it even worse.

So... I think the best course of action here would be to just leave the column as `binary()`.

If you agree, let's close this, I think it's good as-is after https://github.com/Laravel-Backpack/demo/pull/243

**Comment by promatik** [comment]
@tabacitu sorry for the delay. So yes, the code was there before, I just added the table prefix.

But in general, I agree with you, people should not store images on database, we should not promote that 😅
If they really need it, they may create the migration.
We may close this issue ✌

**Comment by pxpm** [comment]
I am not sure you guys saw it, but I submited a PR also yesterday to address this. 

https://github.com/Laravel-Backpack/demo/pull/240

I think @tabacitu opened the issue after I submitted the PR. 

Not sure you guys want to fix it and keep it that way or just want to drop it. Note that @tabacitu delete the whole raw statement, but the `commit` that should be reverted didn't add the `raw` statement there.  The raw statement was added here: https://github.com/Laravel-Backpack/demo/commit/4587452d01455ba3c056871066afa9b8028f23aa#diff-c43a192e5eeef13d59a8b373f2d3eb65fbee5b4b5ed1aea86d17e622273fed4c and it seems is to allow big images, so what I guess is that a 300x300 image would work, but a 1920x1080 wont. 

Let me know.
Pedro

**Comment by promatik** [comment]
@pxpm, yes, @tabacitu end up removing everything.

Now that I think about it once again, this is on `demo`, so there is no point to not provide the ability to those who are testing demo to upload big images, at least they shouldn't get an error when doing it...

@tabacitu maybe we should merge #240 😅

**Comment by tabacitu** [comment]
Hmm... I favoured simplicity, but you guys make a good point:
- It's _the demo_, there's no harm in letting people upload big images in the demo... 
- Plus it'd be frustrating to try uploading a screenshot or "_whatever image you have on hand_" and not be able to.

Ok I agree, let's do #240 - I've added a comment there.

Good catch!
