### ISSUE TITLE
Demo Not working.

### ISSUE THREAD

**Issue by taishjason** [Laravel-Backpack/Demo#25]
Hi, I follow the instruction at here https://laravel-backpack.readme.io/v3.0/docs/demo

But I get the 404 error when I try to go to 

> http://localhost:8000/backpack-demo/public/admin/register

In my  `routes/web.php `

```
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
```
Pls gv some guidance!

**Comment by MarcosBL** [comment]
Isn't there an extra "public" there ? have you tried http://localhost:8000/backpack-demo/admin/register ?

**Comment by OwenMelbz** [comment]
I think this is one of the occasions where somebody has got their WebServer set up in such a way that following documentation is hard!

I've updated the documentation to be less strict and give a suggestion.

I'll close this issue now as github is a place for bug reporting, and this is just a support issue, which you can take over to StackOverflow for help, where people visit the website to help solve peoples issues.
