### ISSUE TITLE
Installation 4.0.* missing adminlte css?

### ISSUE THREAD

**Issue by efsjouw** [Laravel-Backpack/demo#260]
# Bug report

### What I did:

I have used backpack before and simply followed the installation instructions but have never seen this happen before?

Install backpack on Laravel 5.8

composer require backpack/crud:"4.0.*"

### What I expected to happen:

Backpack, adminlte css etc. installed

### What happened:

adminlte css is missing from vendor.

### What I've already tried to fix it:

Tried composer require/install and update again.
Else there is not much I can do?

### Backpack, Laravel, PHP, DB version:

Laravel 5.8
Backpack 4.0.*
PHP 7.1.33
MySQL 5.7.22

**Comment by tabacitu** [comment]
Hey @efsjouw ,

That is correct - in Backpack v4.0 we've moved from AdminLTE to CoreUI (actually a skinned CoreUI we call [Backstrap](https://backstrap.net)). Take a look at the [Backpack 4.0 release notes](https://backpackforlaravel.com/docs/4.0/release-notes) for more details.

If you're starting a new project, I _heavily_ recommend starting with Laravel 8 and Backpack 4.1 though. Take a look at [the Backpack 4.1 release notes](https://backpackforlaravel.com/docs/4.1/release-notes) too - I think there are quite a few things there to get excited about 😀

Cheers!
