### ISSUE TITLE
seeding in install step 3 failed....

### ISSUE THREAD

**Issue by ccyeh0901** [Laravel-Backpack/Demo#28]
Hi, thanks for this wonderful convenient package for us, during installation step 3, when I type comand
$ php artisan db:seed --class="Backpack\Settings\database\seeds\SettingsTableSeeder"

It then show nothing , and no data is generated in the database? Could it be something wrong here? 

besides: I ran the admin demo site well~

**Comment by lloy0076** [comment]
Whilst the artisan command annoyingly doesn't report anything I just installed the demo, did the comman above and saw this:

|![image](https://user-images.githubusercontent.com/1174532/26880028-2163a126-4b61-11e7-983d-4b6b28242c60.png)

I then deleted the data from the database and saw this:

![image](https://user-images.githubusercontent.com/1174532/26880074-4c12d3c4-4b61-11e7-91d8-4a2ae828d368.png)

Then redid the seed and got the first picture back.

Are you looking at the same page?

**Comment by ccyeh0901** [comment]
Ah... I thought it did nothing because artisan responsed nothing but actually it did seeding the database, sorry for my not inspecting code carefully~
