### ISSUE TITLE
Sqlite migration error.

### ISSUE THREAD

**Issue by MusheAbdulHakim** [Laravel-Backpack/demo#287]
# Bug report

### What I did:
After installing the project and running composer install, everything worked fine but when i am running migrations i get this wierd error about a variable in the monsters table migration.
### What happened:
In 2017_04_20_100848_create_monsters_table.php line 27:
                                  
 Undefined variable: columnType  

### What I've already tried to fix it:
I changed from sqlite to mysql and it worked fine
### Backpack, Laravel, PHP, DB version:
sqlite

**Comment by tabacitu** [comment]
Huh - thanks for reaching out @MusheAbdulHakim . I guess we haven't properly tested this demo with SQLite 😀👀😔

I've just created PR https://github.com/Laravel-Backpack/demo/pull/288 which I believe will fix this. Can you confirm it runs correctly with the changes I made in that migration?

Thanks again, cheers!

**Comment by MusheAbdulHakim** [comment]
Still not working. I have the same error after git pulling the updates.

**Comment by MusheAbdulHakim** [comment]
I have fix the issue but the contribution guildelines link on the readme is not working. I was going to send a pr.

**Comment by tabacitu** [comment]
Excellent, thank you @MusheAbdulHakim , merged!
