### ISSUE TITLE
web.php is not what it really like...

### ISSUE THREAD

**Issue by ccyeh0901** [Laravel-Backpack/Demo#29]
Hi, below is the content of web.php

![2017-06-08 10 43 39](https://user-images.githubusercontent.com/16374458/26910119-7dba48ae-4c37-11e7-92e8-ed8160335cbe.jpg)

how could I enter the admin panel through url with the web.php above?
"http://localhost/backpack-demo/public/admin/dashboard"

I just can't figure out how to get the code entry point, please help me out~

ps: below is the result when I type "artisan route:list"
![messageimage_1496889665813](https://user-images.githubusercontent.com/16374458/26910228-2e87df84-4c38-11e7-8ba8-b0f06c653dcf.jpg)

**Comment by lloy0076** [comment]
@ccyeh0901 - remove the `Auth::routes();` (or comment it out).

You can get to the login at http://YOUR_URL/admin/login

Obviously substitute YOUR_URL for something specific to your requirements.

@tabacitu - I think we need to remove the `Auth::routes()` from `routes/web.php`.

**Comment by ccyeh0901** [comment]
thank you, now artisan route:list can list all routes~

**Comment by lloy0076** [comment]
@ccyeh0901 - no, thank you for drawing our attention to it - I've just put up a PR to remove that unneeded `Auth::routes` so eventually others won't have the same experience.

**Comment by jsavalle** [comment]
Just add the same issue - so I commented out - but what I get when I run `php artisan route:list ` is 

```
[ReflectionException]                                                                    
    Class Backpack\PageManager\App\Http\Controllers\Admin\PageCrudController does not exist  
```

**Comment by lloy0076** [comment]
@jsavalle - that sounds like another possible issue - could you please add a new issue (explaining anything that you think may be relevant, especially any _other_ changes that were made)?

**Comment by lloy0076** [comment]
Close due to inactivity.
