### ISSUE TITLE
File manager error

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/demo#3]
When I go to File manager, I get the following error. Do I need to config anything with elfinder?
I have created /public/files directory.

<img width="884" alt="file" src="https://cloud.githubusercontent.com/assets/147320/16741210/972a7826-47a2-11e6-9c12-52baf8213f21.png">

**Comment by tabacitu** [comment]
Hmm... 
1) Have you modified anything in the elfinder.php or filesystem.php config files?
2) Can you try creating an "uploads" folder in /public?

**Comment by shinokada** [comment]
Yes, it worked with /public/uploads folder. Thanks.

**Comment by tabacitu** [comment]
Just added the ```/public/uploads/``` folder with a .gitkeep file, so it won't happen in the future.

Thank you!
