### ISSUE TITLE
[Bug] Chart Widget Error – Load Charts once

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/demo#300]
Using Chart Widget Gives Redeclaration Error!!

Check Demo's Dashboard Page console output.
[https://demo.backpackforlaravel.com/admin/dashboard](url)

```
highcharts.js:10 Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16
    at Object.a.error (highcharts.js:10)
    at highcharts.js:9
    at highcharts.js:10
    at highcharts.js:8
    at highcharts.js:8
```

**Comment by MusheAbdulHakim** [comment]
Now that you have mention it, i have also seen it.

**Comment by tabacitu** [comment]
Good news - this will be solved by https://github.com/Laravel-Backpack/CRUD/pull/2652 in 4.2 - automatically 🎉 So I'm going to close this. Thank you for raising the issue @karandatwani92 🙏
