### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by zidingz** [Laravel-Backpack/demo#301]
Hey there!

I belong to an open source security research community, and a member (@aravindd007) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by promatik** [comment]
Hi @zidingz!
Thank you for your interest and concern 🙌

To report security issues please email hello@tabacitu.ro.

This is a demo project for our main repo, CRUD, we have the [`SECURITY.md`](https://github.com/Laravel-Backpack/CRUD/blob/master/SECURITY.md) there.

**Comment by tabacitu** [comment]
Yup - I'm the one. Please contact the email above @zidingz .

Cheers!
