### ISSUE TITLE
PageCrudController does not exist

### ISSUE THREAD

**Issue by jsavalle** [Laravel-Backpack/Demo#32]
Hi,

I have the current issue:

I have followed the instructions for the demo install.
Namely:
```
$ git clone https://github.com/Laravel-Backpack/demo.git backpack-demo
```
The fixed the .env with the db info.
```
$ composer install
$ php artisan key:generate
$ php artisan migrate
$ php artisan db:seed --class="Backpack\Settings\database\seeds\SettingsTableSeeder"
```

Once this was done - I tried to get 
MYURL/backback-demo/public/admin/register 
or 
MYURL/backback-demo/public/admin/

But I would get 404 each time.

Checking open issues - I read that commenting out the Auth::routes(); in web.php - might

well... it didn't

when I run `php artisan route:list`, I get

```
[ReflectionException]                                                                    
    Class Backpack\PageManager\App\Http\Controllers\Admin\PageCrudController does not exist  
```

So I don't know what might have gone wrong.
Is there a bug? Am I really not doing it right... don't know...

**Comment by AbbyJanke** [comment]
I checked this, and yes, `Auth::routes()` needs to get commented out, however I was getting

```
[ReflectionException]                                     
  Class App\Http\Controllers\HomeController does not exist
```

instead of PageCrudController. Can you confirm that is correct? Basically all that I within my web.php routes file is:

```
Route::get('/', function () {
    return view('welcome');
});
```

**Comment by tabacitu** [comment]
Hi @jsavalle ,

I tested @AbbyJanke 's solution and it seems to fix your problem, so I'll close this issue.
Feel free to reply if it doesn't.

Cheers!
