### ISSUE TITLE
[4.2] New entities to highlight all relationship types

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/demo#339]
Even after https://github.com/Laravel-Backpack/demo/pull/313 and https://github.com/Laravel-Backpack/demo/pull/218 ... I don't think we're doing a good enough job at showing off all relationships. I still can't figure them out in the examples in https://github.com/Laravel-Backpack/demo/pull/218, and I've had my nose in them for a month now. I think the best thing we can do is create some new entities, similar to what one would build in real life, to show ALL possible Laravel relationships (both the ones we support and the ones we don't).

Here's what I propose - @pxpm please 
- [ ] **tell me if you think any of them are wrong/unrealistic**
- [ ] **tell me if you have a better example**
- [ ] **tell me if I've missed any Laravel relationships**

I don't want to you do anything about this other than give feedback. Don't want _you_ to code these CRUDs, _I_ want to do it first, because in the process I'll test them out. Here's my train of thought:

## 1. What relationships do we support?

Standard relationships:
- 1-1
    - [x] `hasOne`
    - [x] `belongsTo` (inverse)
- 1-n
    - [x] `hasMany`
    - [x] `belongsTo` (inverse)
- n-n
    -  [x] `belongsToMany`
    -  [x] `belongsToMany` with extra attributes on pivot table

Polymorphic relationships:
- 1-1
    -  [x] `morphOne`
    -  [x] `morphTo` (inverse)
- 1-n
    -  [x] `morphMany`
    -  [x] `morphTo` (inverse)
- n-n
    -  [x] `morphToMany`
    -  [x] `morphToMany` with extra attributes on pivot table
    -  [x] `morphedByMany` (inverse)

## 2. What relationships do we NOT support?

The following relationships are NOT supported by Backpack fields. Why? Because they are read-only relationships. Fields are meant for creating&editing, not reading. These will still work in columns (reading), but not in fields (creating&editing):
- [x] passthrough relationships:
    - [x] `hasOneThrough`
    - [x] `hasManyThrough`
- [x] One of Many (eg. `hasOne(Order::class)->latestOfMany()`)
- [x] Morph One of Many (eg. `morphOne(Image::class)->latestOfMany`)

## 3. What's a good example of each supported relationship?

Here's my first draft. It's **a community of pet owners, their pets and the things they purchase for them**. I've made [an interactive diagram of the db tables needed](https://drawsql.app/backpack/diagrams/relationships-demo-persons-invoices#) and here's a screenshot of it with the Laravel relationships in red:

![Screenshot 2022-01-05 at 13 38 50](https://user-images.githubusercontent.com/1032474/148213515-7b07ac1a-f706-484d-bb53-00fc866167b9.png)

I _believe_ it contains all relationships mentioned above:

- Standard 1-1:
    - Pet... `hasOne`... Passport (`person_id` on `passports` table)
    - Passport... `belongsTo`... Pet (inverse of the above)
- Standard 1-n:
    - Owner... `hasMany`... Invoice (`owner_id` on `invoices` table)
    - Invoice... `belongsTo`... Owner (inverse of the above)
    - Invoice... `hasMany`... InvoiceItem (`invoice_id` on `invoice_items` table)
    - InvoiceItem... `belongsTo`... Invoice (inverse of the above)
- Standard n-n:
    - Pet... `belongsToMany`... Skill
    - Skill... `belongsToMany`... Pet (inverse of the above)
    - Owner... `belongsToMany`... Pet (with an extra `role` on the pivot table)
    - Pet... `belongsToMany`... Owner (inverse of the above)
- Polymorphic 1-1 (Owners and Pets can have Avatars):
    -  Owner `morphOne` Avatar
    -  Avatar `morphTo` Owner (inverse)
    -  Pet `morphOne` Avatar
    -  Avatar `morphTo` Pet (inverse)
- Polymorphic 1-n (Pets, Owners and Comments can have Comments):
    -  Pet `morphMany` Comment (`commentable`)
    -  Comment `morphTo` Pet (inverse)
    -  Owner `morphMany` Comment (`commentable`)
    -  Comment `morphTo` Owner (inverse)
    -  Comment `morphMany` Comment (`commentable`)
    -  Comment `morphTo` Comment (inverse)
- Polymorphic n-n (Pets and Owners can have Badges):
    -  Pet `morphToMany` Badge
    -  Badge `morphedByMany` Comment (inverse)
    -  Owner `morphToMany` Badge (with extra `note` on pivot table)
    -  Badge `morphedByMany` Owner (inverse)
- _unsupported_ passthrough relationships:
    - InvoiceItem `hasOneThrough` Owner through Invoice
    - Pet `hasManyThrough` Invoice through Owner
- _unsupported_ One of Many (Owner `hasOne(Invoice::class)->latestOfMany()` Invoice - `latestInvoice()`)
- _unsupported_ Morph One of Many (Owner `morphOne(Comment::class)->latestOfMany` - `latestComment()`)

**How does this look to you @pxpm ? Is this relatable/easy-to-understand or difficult?** Any idea on how we can do better?

**Comment by tabacitu** [comment]
After going through all relationship types and trying to figure out examples for them, I think I've identified a problem with our relationship field: it's difficult to understand when the interface will change from "selecting" to "editing". Or at least not clear enough for me _yet_. Or not documented well. I'll come back with a more certain opinion after I actually implement all of the above. But until then, here are my thoughts on this. **There are TWO WAYS of looking at RELATIONSHIP FIELDS (from a DEV point of view):**

## (A) Use the `relationship` field for everything about relationships

- if I want to select one or more relationships, I use the `relationship` field:
```php
CRUD::field('comments');
```
- if I want to edit the fields on a relationship, I use the same `relationship` field and also define the `fields` attribute;

(seems to be the current implementation, but fails for some relationships - eg. `HasOne`)

## (B) Different fields for different interfaces

- if I want to select one or more relationships, I use the `relationship` field:
```php
CRUD::field('comments');
```
- if I want to edit the fields on a relationship, I use the `relationship_editor` (or `related_entries`) field:
```php
CRUD::field('comments')->type('relationship_editor')->fields([
    'title',
    [
        'name' => 'body',
        'type' => 'textarea',
    ],
    [
        'name' => 'created_by',
        'label' => 'Author',
        'type' => 'select',
    ]
]);
```

---

Again, I'll come back on this after I code all relationship types. It's just something that I found confusing while trying to understand the relationship field.

**Comment by pxpm** [comment]
When working with relationships fields you don't define the type of the field. 

That's abstract, it's just Backpack working in the background, when working with relationships only the relationship name and aditional configurations should be provided. 

So it's assumed that: 
- If you don't provide aditional configuration you will get a select (for ALL the `...Many` relations). 
- if you add the `pivotFields` configuration backpack will create a repeatable for those fields and setup some aditional configurations depending on the relation type.
- belongsto is a mandatory select with option to inline_create a new entry. 
- hasOne/morphOne are defined as dot notation because we should be able to handle a relations inside an hasOne/morphone for example: user -> hasone -> address -> (address.country) -> belongsto -> country.

**Comment by tabacitu** [comment]
I understand that now, but it took me quite a while to figure that out. With the current implementation/naming, there are a lot of asterisks to the relationship field. I foresee people banging their heads on their desks 😀 I'm trying to see if there's a way to rephrase the docs (or split the functionality) to prevent that from happening 😅  I don't have any bright ideas at the moment, maybe after I use the `relationship` field in all use cases, a more intuitive way will come to me 🤞 

Until then, please give a hard look at the example I provided above and let me know if you think it's ok (I should code it). Or if there are any changes you think are needed to make it easier to understand, or highlight a relationship functionality I missed.

**Comment by pxpm** [comment]
Hey @tabacitu about the scenario you described I think the only thing that needs a little improvement is the `belongsToMany` and `MorphToMany` relations since they should show why a pivot table is in use: **they can handle the same relation for "many" different entities**, what I mean is just to add another entity that can make use of the pivot table, for example `avatars` could be `badgeables` too to show two diferent entities using the relation. Same for BelongsToMany where you have only one entity using the pivot. 

Apart from that it seems a very good example that will show off the relationships. 👍

**Comment by tabacitu** [comment]
Hmm... I don't quite understand what you're suggesting @pxpm ... could you please rephrase?

**Comment by pxpm** [comment]
Rephrasing: 

MorphToMany is used when the same entity (badge) can belong to different entities (avatars or comments for example). If not using polymorphic relations you would split this into two BelongsToMany with two different pivot tables: avatars_bagdes and badges_comments instead of the single `badgeables`. 

So in the end my suggestion is to make `avatars` `badgeable` too so we show why use the polymorphic relation. I think we should show this behaviour is what I meant 👍 sorry for the confusion.

**Comment by tabacitu** [comment]
Ah, ok, I understand, thank you 🙏  We already have `owners` `badgeable` and `pets` `badgeable` (two entities), so I think the polymorphic relationship is properly shown off here, no need for `avatars` to be `badgeable` too (a third entity). 

You must have missed one of them in the diagram... or maybe I didn't mention that in the text. I think we're good here!

**Comment by tabacitu** [comment]
PR here https://github.com/Laravel-Backpack/demo/issues/339
