### ISSUE TITLE
Reorder fields in Monster (reduce clutter)

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/demo#344]
Let's reorder them like this:

```
SIMPLE
TIME AND SPACE
RELATIONSHIPS
    - hasOne (1-1)
        - relationship [street, country, postal_code]
        - relationship + subfields
    - belongsTo (n-1)
        - relationship
    - hasMany (1-n)
        - relationship
        - relationship + subfields
    - belongsToMany (n-n)
        - relationship
        - relationship + subfields
    - morphOne (1-1)
        - relationship
        - relationship + subfields
    - morphMany (1-n)
        - relationship
        - relationship + subfields
    - morphToMany (n-n)
        - relationship
        - relationship + subfields
    - extra relationship features (ajax and inlineCreate)
        - belongsTo relationship + ajax + inlineCreate
        - belongsToMany relationship + ajax + inlineCreate
        - belongsToMany relationship + subfields + ajax + inlineCreate
SELECTS
    - select
    - select2
    - select_from_array
    - select2_from_array
    - select_and_order
    - select_grouped
    - select2_grouped
    - select2_nested
    - select2_from_ajax
    - select_multiple
    - select2_multiple
    - select2_from_ajax_multiple
    - checklist
UPLOADS
BIG TEXTS => rename to WYSIWYG Editors
MISCELLANEOUS => Others (maybe)
```

**Comment by tabacitu** [comment]
@pxpm I just remembered you asked if we can add new entities/columns/relationships in the demo. And I said "yes". It's still a "yes", but I hope you don't go overboard 😅  I'm ok with adding new stuff, but we're trying to make the Demo _easier to understand_, not _more difficult_. So please:
- don't add too many stuff
- if you do add stuff, add them in a way that is easy to understand (plausible entities, with plausible fields and plausible relationships); we shouldn't make the viewer _think_, entities and relationships should feel _natural_, _intuitive_;

I was adding some entities myself in https://github.com/Laravel-Backpack/CRUD/issues/4109 and felt like this needed to be said. That's the direction for the demo - clearer. Easier to understand.

**Comment by pxpm** [comment]
@tabacitu I am creating more Models so their relations don't overlap, what I mean is: don't have the same relation on both models, and also don't use the same model for the relations. 

I know they don't make "sense", and are far way from reality, but I am just adding them for the Monster, where we show of everything, so it's also easy to find something if we have different relation names for each field, so basically you search the field name in the project and will get the relation definition plus the field definition on your search results. 

I am building this Monsters as the "test bed" for stuff, I think PetShop is an example we can evolve to really show as a demo and Monsters would fallback to be the "cheatsheet" for CRUD fields. 

Let me know if my reasoning here is wrong.

**Comment by tabacitu** [comment]
It's done in https://github.com/Laravel-Backpack/demo/pull/345 but it still needs some polish.
