### ISSUE TITLE
Custom dashboard not working

### ISSUE THREAD

**Issue by InkedCurtis** [Laravel-Backpack/Demo#37]
I've added the following to my **routes.php** file:

```php
Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin')
], function () {
    Route::get('dashboard', 'DashboardController@overview');
});
```

I've also changed the order of my providers inside **config/app.php** to the following:

```php
Backpack\Base\BaseServiceProvider::class,
App\Providers\RouteServiceProvider::class,
```

Yet it still appears to be showing me the same dashboard? I can't seem to get the dashboard to become a handler yet it works if I do something like:

```php
Route::get('test', 'TestController@overview');
```

**Comment by OliverZiegler** [comment]
Try using the new overwrite functionality for routes. Just copy the original routes and replace the ones that should differ.

> create a routes/backpack/base.php file; the package will see that, and load your routes file, instead of the one in the package;
