### ISSUE TITLE
\backpack-demo/.env): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by miadz** [Laravel-Backpack/Demo#40]
php artisan key:generate

  [ErrorException]
  file_get_contents(C:\xampp\htdocs\backpack-demo/.env): failed to open stream: No such file or directory

**Comment by lloy0076** [comment]
@miadz - does that file exist at all?

**Comment by enimiste** [comment]
It is better to use Homestead to run your laravel projects to avoid paths missmutching between Windows and linux.

**Comment by tabacitu** [comment]
Hi @miadz - sounds to me like a server configuration error, so I'll close this issue. I notice the path contains both slashes and backslashes - that might be the problem. Hope it helps. 

Feel free to reopen it if I'm wrong and it's a Backpack-related problem.

Cheers!
