### ISSUE TITLE
laravel_session keeps changing values when refreshing

### ISSUE THREAD

**Issue by ccyeh0901** [Laravel-Backpack/Demo#42]
Thanks for making such a wonderful package.
I noticed that when after login and I observe the cookie value of  laravel_session key, it keep changing  everytime i refresh the page, is that normal? though things are going on well. Sorry if this question is too trivial to be a issue.

**Comment by tabacitu** [comment]
Hi @cceglia ,

Sorry for noticing so late. Yup, that's normal. It's the default Laravel implementation - nothing we do about it there :-)

Cheers!
