### ISSUE TITLE
Demo install

### ISSUE THREAD

**Issue by tspyra** [Laravel-Backpack/demo#424]
I can't install the demo. My username and password not working.
![Bez tytułu](https://user-images.githubusercontent.com/114303881/192207671-9d08aef1-0f3b-4cfa-8c3f-f041a95dc890.jpg)

**Comment by pxpm** [comment]
Hello @tspyra 

The demo uses 2 paid packages (PRO and Editable Columns). You need access to both of them to install the demo.
I think you may be lacking access to Editable Columns package. 

You can download the demo, remove the editable columns package from composer.json and remove the `EditableMonsterCrudController` or comment out the `UpdateMinorOperation` trait. 

Run composer update again and you should get the demo working. 

Let me know if that's not the case and we can re-open this issue.

Cheers

**Comment by tspyra** [comment]
It works. Thank you.
