### ISSUE TITLE
 Class Backpack\Base\Backpack\Base\app\Console\Commands\Install does not exist

### ISSUE THREAD

**Issue by martinym28** [Laravel-Backpack/Demo#43]
# Bug report  Class Backpack\Base\Backpack\Base\app\Console\Commands\Install does not exist

**Comment by MilitaruC** [comment]
Same thing here. On Installation I got this:

Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

  [ReflectionException]
  Class Backpack\Base\Backpack\Base\app\Console\Commands\Install does not exist

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by tabacitu** [comment]
Hi guys,

Thanks for telling us. The issue has since been fixed (a few hours after your first report). A ```composer update``` should fix it for you.

Cheers!
