### ISSUE TITLE
Roles not working on Demo

### ISSUE THREAD

**Issue by promatik** [Laravel-Backpack/demo#447]
# Bug report

https://demo.backpackforlaravel.com/admin/role

![image](https://user-images.githubusercontent.com/1838187/204868927-cb903206-9514-4930-99cb-3c0b2cd80f49.png)

It's an SQL error;

``
SQLSTATE[HY093]: Invalid parameter number (SQL: select count(*) as total_rows from (select `roles`.`id`, (select count(*) from `users` inner join `model_has_roles` on `users`.`id` = `model_has_roles`.`model_id` where `roles`.`id` = `model_has_roles`.`role_id` and `model_has_roles`.`model_type` = ?) as `users_count` from `roles`) as `roles_aggregator`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: HY093): SQLSTATE[HY093]: Invalid parameter number (SQL: select count(*) as total_rows from (select `roles`.`id`, (select count(*) from `users` inner join `model_has_roles` on `users`.`id` = `model_has_roles`.`model_id` where `roles`.`id` = `model_has_roles`.`role_id` and `model_has_roles`.`model_type` = ?) as `users_count` from `roles`) as `roles_aggregator`) 
``

**Comment by pxpm** [comment]
Not fast enough! https://github.com/Laravel-Backpack/CRUD/pull/4796

heheh cheers!
