### ISSUE TITLE
Bug "Unable to get property 'innerHTML' of undefined or null reference" on Monsters page

### ISSUE THREAD

**Issue by enimiste** [Laravel-Backpack/Demo#46]
# Bug report

### What I did:
List all monsters. Then i clicked on Copy|Excel|Csv|Pdf buttons

### What I expected to happen:
Export excel
Export csv
...

### What happened:
Nothing.
But on my browser console i had this error message : Unable to get property 'innerHTML' of undefined or null reference dataTables.buttons.min.js (34,22)

### What I've already tried to fix it:
None
### Backpack, Laravel, PHP, DB version:
"php": ">=7.0",
        "laravel/framework": "5.5.*",
        "backpack/base": "^0.8.0",
        "backpack/crud": "^3.3.0",
        "backpack/backupmanager": "^1.1",
        "backpack/logmanager": "^2.3",
        "backpack/settings": "^2.0",
        "backpack/pagemanager": "^1.1",
        "backpack/MenuCRUD": "^1.0",
        "backpack/newscrud": "^2.1",
        "backpack/permissionmanager": "^2.1"

**Comment by tabacitu** [comment]
Hmm that's odd. Works as expected for me: https://cl.ly/3h3z3x1F0w0l

1) Did this happen on a newly-installed Demo project or on an upgraded one (from 3.2 to 3.3)?
2) Anybody else having this problem?
3) What OS and browser are you using?

Thanks, cheers!

**Comment by enimiste** [comment]
I created a new laravel/laravel 5.5 project
Then i followed the installation here : [https://laravel-backpack.readme.io/docs/install-on-laravel-55](https://laravel-backpack.readme.io/docs/install-on-laravel-55)
Then this tutorial : [https://laravel-backpack.readme.io/docs/crud-example](https://laravel-backpack.readme.io/docs/crud-example)
I tested it and works well then i added this line `$this->crud->enableExportButtons();` to show exports buttons.
But when i click on these buttons i get the same error message.

My controller code :
`
class TagCrudController extends CrudController
{
    /**
     *
     */
    public function setup()
    {
        $this->crud->setModel(Tag::class);
        $this->crud->setRoute('admin/tag');
        $this->crud->setEntityNameStrings('tag', 'tags');

        $this->crud->setColumns(['name']);

        $this->crud->addField([
            'name' => 'name',
            'type' => 'text',
            'label' => 'Tag name'
        ]);

        $this->crud->enableExportButtons();
    }

    /**
     * @param TagCrudRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(TagCrudRequest $request)
    {
        return parent::storeCrud($request);
    }

    /**
     * @param TagCrudRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(TagCrudRequest $request)
    {
        return parent::updateCrud($request);
    }
}
`
My model code :
`
class Tag extends Model
{
    use CrudTrait;

    protected $fillable = ['name'];
}

`

**Comment by enimiste** [comment]
NB : I serve my project from Homestead [HEAD  f40f5f7] with a local domaine backpack.app:8000

**Comment by enimiste** [comment]
I think the issue is only on Microsoft Edge browser.
I tester on Chrome, FireFox and Internet Explorer and works well.

I think this is an issue to be fixed by the datatables team.
But it will be a good information to make an info on the documentation to notify people to not test on Microsoft Edge. I will propose it

**Comment by tabacitu** [comment]
Oh, ok. Thanks for the bug report and the update @enimiste . If it's an Edge issue, it's one for the DataTables team, yes.

Cheers!
