### ISSUE TITLE
Error message from datatables when opening settings menu

### ISSUE THREAD

**Issue by enimiste** [Laravel-Backpack/Demo#47]
# Bug report

### What I did:
Click on Settings menu

### What I expected to happen:
List all settings and manage theme

### What happened:
Get the message attached below

### What I've already tried to fix it:
None
![capture](https://user-images.githubusercontent.com/2515677/32605478-7b784524-c549-11e7-9732-9b194beb06dd.PNG)

**Comment by tabacitu** [comment]
Hi @enimiste ,

Thank for reporting this. The issue has since been fixed an Settings is now Backpack 3.3 compatible too. A ```composer update``` should fix it for you.

Cheers!
