### ISSUE TITLE
Error when runing php artisan make:migration:schema

### ISSUE THREAD

**Issue by enimiste** [Laravel-Backpack/Demo#48]
# Bug report and information

### What I did:
`php artisan make:migration:schema create_tags_table --model=0 --schema="name:string:unique" `
### What I expected to happen:
Execution without errors
### What happened:
`[ReflectionException]
  Method Laracasts\Generators\Commands\MigrationMakeCommand::handle() does not exist`
### What I've already tried to fix it:
The issu is related to the [laracasts/Laravel-5-Generators-Extended](https://github.com/laracasts/Laravel-5-Generators-Extended) package that those not implements handle function in its console commande. And this demo project was based on Laravel 5.5 that requires the handle function instead of fire.
For that i sent a pull request to the Jeffery
[https://github.com/laracasts/Laravel-5-Generators-Extended/pull/143](https://github.com/laracasts/Laravel-5-Generators-Extended/pull/143)

**Comment by tabacitu** [comment]
Yup, I did so too, on Aug 30th, but hasn't been merged yet - https://github.com/laracasts/Laravel-5-Generators-Extended/pulls

**Comment by tabacitu** [comment]
Hi @enimiste - good news bad new. Good new is that we've now been given write access to Jeffrey Way's repository and we fixed this. All works fine now. Bad news is we have yet another repository to maintain :-)

Cheers!
