### ISSUE TITLE
Upload to S3

### ISSUE THREAD

**Issue by girishkv** [Laravel-Backpack/Demo#5]
how can move the files to S3 ?, I tried  with type=browse, in Cruds controller, its not working. I've given proper credentials in filesystem.php and set default to s3 & fset cloud to s3.

**Comment by tabacitu** [comment]
Hi @girishkv  

The CRUD package uses elFinder for the file manager your see in the "browse" field. In order for the file manager to also show your s3 bucket, you need to tell elFinder that, in your config/elfinder.php:

```php
'disks' => [
         's3', // or whatever your disk name is
    ],
```

Cheers!

**Comment by tabacitu** [comment]
Hi @girishkv ,

Does that solve it for you? Can I close the issue?

Cheers!

**Comment by girishkv** [comment]
Yea...! its solved. Thanks a lot

**Comment by Himani-Bhatt** [comment]
how to use s3 as storage disk?
can anyone plzz give me sample code...

**Comment by lloy0076** [comment]
The responses above should be enough to figure out how to configure elfinder.

If you're asking how to use S3 as a storage disk in general, consult the Laravel documentation or S3's documentation.
