### ISSUE TITLE
Toggle for theme in demo

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/demo#509]
What if in addition to being able to choose the layout (in tabler theme) we also give the Demo user the ability to choose... 🥁🥁🥁... THE THEME?!

**Comment by maurohmartinez** [comment]
@tabacitu and...... 🥁 🥁 🥁 

![demo-switch-themes](https://github.com/Laravel-Backpack/demo/assets/33960976/f8becc1c-e2d6-47c0-aaf2-087dfffbf128)
