### ISSUE TITLE
Dropzone is usable in our online demo

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/demo#548]
# Bug report

### What I did:

Went to https://demo.backpackforlaravel.com/admin/monster/140/edit#uploads

### What I expected to happen:

Expected the Dropzone to be disabled, unusable or something.

### What happened:

I could upload files... or at least it looks like it:
<img width="1491" alt="CleanShot 2023-07-14 at 08 22 56@2x" src="https://github.com/Laravel-Backpack/demo/assets/1032474/7aa71a62-d55c-47ca-8693-57fa5ce9fef9">

**Comment by tabacitu** [comment]
@pxpm didn't we already take care of this?

**Comment by pxpm** [comment]
We took, I am sure you disabled them after I created the mutators to disable the uploading process. 

I will have a look at it 👍

**Comment by pxpm** [comment]
It's buggy, but no files were uploaded. 

fixed in #549
