### ISSUE TITLE
JS Components not working in online demo

### ISSUE THREAD

**Issue by EmanueleCoppola** [Laravel-Backpack/demo#552]
# Bug report
JS components not working in demo

### What I did:
Visited
- https://demo.backpackforlaravel.com/admin/editable-monster/create#wysiwyg-editors
- https://demo.backpackforlaravel.com/admin/cave/create

### What I expected to happen:
See all the JS components working.

### What happened:
None of the JS components is working.
I also see many 404 in the console, my guess is that basset might be broken.

**Comment by tabacitu** [comment]
Thanks for the report @EmanueleCoppola ! We'll investigate and fix ASAP 🙏 Probably today.

**Comment by tabacitu** [comment]
Possible causes:

1) Cloudflare's Rocket Loader
2) Our "database refresh" script
3) Maybe some hits being made WHILE we are deploying? So while `php artisan basset:fresh` is being run, people WILL access direct URLs, so Basset will internalize some JS/CSS twice, and maybe that causes some conflicts? We can eliminate this by running `php artisan down` and `php artisan up` in our deploy and refresh scripts. But then we need to create a clear Error 500 page so people know what is happening.

**Comment by tabacitu** [comment]
@EmanueleCoppola I believe we've fixed it. I'm not 100% but I am 99% sure so I'll close this 😀 You can see WHY this has happened in https://github.com/Laravel-Backpack/demo/pull/553#issuecomment-1648337127 

Thanks again for opening this up!

**Comment by tabacitu** [comment]
@karandatwani92 feel free to check our demo once in a while, and tell me if we're still having problems. But we should be good to go now.
