### ISSUE TITLE
error when migrate

### ISSUE THREAD

**Issue by lili94** [Laravel-Backpack/Demo#57]
```
 [Illuminate\Database\QueryException]
 SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i
 n your SQL syntax; check the manual that corresponds to your MariaDB server
  version for the right syntax to use near 'json not null, `description` jso
 n null, `details` json null, `features` json nul' at line 1 (SQL: create ta
 ble `products` (`id` int unsigned not null auto_increment primary key, `nam
 e` json not null, `description` json null, `details` json null, `features`
 json null, `price` int not null, `category_id` int not null, `extras` json
 null, `created_at` timestamp null, `updated_at` timestamp null) default cha
 racter set utf8 collate utf8_unicode_ci)
```
 please help

**Comment by lili94** [comment]
fixed maria-db don' t support json change in product json to text

**Comment by abdallahmaali** [comment]
i have same problem how you fixed it ?

**Comment by tabacitu** [comment]
As far as I know MariaDB doesn't support JSON columns. If you're using that in your migrations, switch to using ```text``` columns instead.

Hope it helps. Cheers!

**Comment by lloy0076** [comment]
https://mariadb.com/kb/en/library/json-data-type/


> The JSON alias was added in MariaDB 10.2.7. This was done to make it possible to use JSON columns in statement based replication from MySQL to MariaDB and to make it possible for MariaDB to read mysqldumps from MySQL.

For reference.

**Comment by ccyeh0901** [comment]
Hello, mine is mysql 5.6.35 but the same error message shown up when doing "artisan migrate"... 
I did solve the bug as lili94 suggested changed json to text type, thanks~

**Comment by upeksha1996** [comment]
@ccyeh0901 mysql version should be atleast 5.7.* to use json

**Comment by emtiazzahid** [comment]
MariaDB 10.2 supported JSON. (Alpha version. Not recommended by Maria to production server. Only testing.)

MariaDB 10.1 do not support JSON (
