### ISSUE TITLE
Demo's file manager icons are missing 404

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/demo#574]
Demo's file manager icons are missing 404

Works fine on local ✅
I assume we just need to run:
`php artisan basset:clear && php artisan basset:fresh`

https://demo.backpackforlaravel.com/admin/elfinder#elf_l1_Lw

![Screenshot 2023-09-02 at 1 53 33 PM](https://github.com/Laravel-Backpack/demo/assets/8214221/d7f14eb5-45d5-4164-abdf-f98a84fef6a2)
![Screenshot 2023-09-02 at 1 53 56 PM](https://github.com/Laravel-Backpack/demo/assets/8214221/3aa4dc81-943d-4918-9dd4-9cc24dc5c728)

**Comment by tabacitu** [comment]
Can confirm the problem, but I've just apparently that's already in the deployment pipeline... so that might not be the problem. I've just run `php artisan basset:fresh` manually on the demo... that didn't fix it either. 

It could be a CloudFlare thing... maybe? 🤷‍♂️

**Comment by karandatwani92** [comment]
The Nested menu is also broken in the **online demo for mobile view.** The desktop view is fine.
**On local** both issues don't persist.

I suspect the cause is similar - related to JS/CSS cache

**Comment by tabacitu** [comment]
@pxpm / @promatik can you take this over please?

**Comment by pxpm** [comment]
Fixed in https://github.com/Laravel-Backpack/FileManager/pull/42

I am still investigating the nested dropdown issue, will submit a PR/open an separate issue for it.
