### ISSUE TITLE
errors on last demo

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/demo#580]
I find some errors in the latest demo https://github.com/Laravel-Backpack/demo/commit/726ae90295c4ad3979a67404891c53edb7f13a47

Sent as feedback

<img width="1634" alt="bkp-demo-errors" src="https://github.com/Laravel-Backpack/demo/assets/1261851/7792855e-203c-4626-a5ae-cd9c56f9a7f4">

**Comment by phpfour** [comment]
Hey @blondie63, thanks for posting here. 

I am unable to locate the problem here – the demo seems to work correctly and I do not see any errors on the console. 

Can you help me to reproduce the issue?

**Comment by blondie63** [comment]
Hi @phpfour yes demo is starting fine also on my local but when i open code using vs.studio i seen some red errors like these:
<img width="363" alt="bkp-demo-i1" src="https://github.com/Laravel-Backpack/demo/assets/1261851/f064fe6c-5cbd-4316-9c52-53b45a8780cd">
<img width="415" alt="bkp-demo-i2" src="https://github.com/Laravel-Backpack/demo/assets/1261851/4762808e-8d2a-4ca6-a9e7-4c8cee91fead">

Could it be a VS.Studio error?

**Comment by phpfour** [comment]
> Could it be a VS.Studio error?

Maybe...I don't use VS Studio so I can't really comment. One thing to notice is that the tooltip is detecting the code block as `javascript` so most likely that's causing the editor to think its wrong.

Anyway, I am closing the issue as there's no next action required.
