### ISSUE TITLE
Laravel Collective is Missing

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/Demo#59]
# Bug report

### What I did:

Install the Demo.

### What I expected to happen:

It works!

### What happened:

It doesn't because something still required `laravelcollective/html`.

### What I've already tried to fix it:

Added to `composer.json`:

```
"laravelcollective/html":"5.5.1"
```

### Backpack, Laravel, PHP, DB version:

Probably the current one.

### Proposed Fix

Add it back!

### Other Comments

I suspect the actual bug is in one of the dependencies however the quick demo fix is noted here.

**Comment by tabacitu** [comment]
Update: this only fails after a ```composer update```

**Comment by tabacitu** [comment]
Ok so I got to the bottom of this. In the Demo, the service provider for this package is registered in ```config/app.php```. And it should be deleted from there. That's what's causing the issue.

I'm currently pushing the upgrade to CRUD 3.4 and Laravel 5.6, and this fix is already implemented there. So I'll close this.

Thanks, cheers!
