### ISSUE TITLE
Add C3 and Fusioncharts example charts to demo

### ISSUE THREAD

**Issue by eastonmeth** [Laravel-Backpack/demo#591]
Currently, there is only ChartJS, Echarts, Frappe and Highcharts examples in the demo but there is nothing to be found for C3 or Fusioncharts, despite them being listed as valid charting libraries in the documentation.

[Laravel Backpack Documentation - Chart PRO](https://backpackforlaravel.com/docs/6.x/base-widgets#chart-pro)
[Laravel Backpack Demo Repository - Charts Directory](https://github.com/Laravel-Backpack/demo/tree/main/app/Http/Controllers/Admin/Charts)

**Comment by tabacitu** [comment]
Hey @eastonmeth ,

Good catch! When I created the dashboard page, I didn't quite like C3 and FusionCharts... hence I didn't include them in the demo (or any of my projects). If you do, go ahead, they're supported! 

To be honest, I don't even remember WHY I didn't like them. But I'm going to trust my past self on it 😅 The syntax to use them isn't different at all, just the way they look is different. So for brevity, I'd rather keep the dashboards with the charts we have now.

Cheers!
