### ISSUE TITLE
Laravel Backpack update to 3.3 leads to BadMethodCallException (Method Illuminate\Database\Query\Builder::save does not exist) 

### ISSUE THREAD

**Issue by daswanihimanshu010** [Laravel-Backpack/Demo#60]
# Bug report: BadMethodCallException
Method Illuminate\Database\Query\Builder::save does not exist.

### Backpack, Laravel, PHP, DB version:
"backpack/base": "^0.9.2",
"backpack/crud": "^3.3.0",
Laravel: 5.5
Php: 7.2

**Comment by tabacitu** [comment]
Hi @daswanihimanshu010 ,

This error doesn't make any sense to me - I don't see how the ```save()``` method can be lacking on an Eloquent model... Tried it myself and it works... no error. I wonder if it's not some modifications you've done to the Model or your EntityCrudController?

I don't know, I really don't know...
