### ISSUE TITLE
Get json Error on migration product table 

### ISSUE THREAD

**Issue by emtized** [Laravel-Backpack/Demo#63]
When i tried to migrate clean project i got this error on json field on product tabel : 

`In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds t
  o your MariaDB server version for the right syntax to use near 'json not null CHECK (JSON_VALID(`name`)), `description` json null
   CHECK (`descri' at line 1 (SQL: create table `products` (`id` int unsigned not null auto_increment primary key, `name` json not
  null CHECK (JSON_VALID(`name`)), `description` json null CHECK (`description` IS NULL OR JSON_VALID(`description`)), `details` js
  on null CHECK (`details` IS NULL OR JSON_VALID(`details`)), `features` json null CHECK (`features` IS NULL OR JSON_VALID(`feature
  s`)), `price` int not null, `category_id` int not null, `extras` json null CHECK (`extras` IS NULL OR JSON_VALID(`extras`)), `cre
  ated_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')

In PDOConnection.php line 82:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds t
  o your MariaDB server version for the right syntax to use near 'json not null CHECK (JSON_VALID(`name`)), `description` json null
   CHECK (`descri' at line 1

In PDOConnection.php line 80:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds t
  o your MariaDB server version for the right syntax to use near 'json not null CHECK (JSON_VALID(`name`)), `description` json null
   CHECK (`descri' at line 1

`
My Database version is : 10.1.32-MariaDB

**Comment by zwibowo** [comment]
same problem here, how to solve this ?

**Comment by zwibowo** [comment]
@emtized i have a solution, and success migrate without error.

change json to text, in database/migration/xxxxxxx_product_table.php

**Comment by tabacitu** [comment]
@emtized looks like your MariaDB doesn't support JSON columns. An update to the latest MariaDB should fix it for you.

Cheers!
