### ISSUE TITLE
PET/OWNER Nested CRUD Example is broken

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/demo#660]
# Bug report

While writing an article on Nested CRUD, I found the following:
- `OwnerPetsCrudController` lists empty results.
-  All Operations need a check -- Create, Edit, etc.

https://demo.backpackforlaravel.com/admin/pet-shop/owner/5/pets
https://demo.backpackforlaravel.com/admin/pet-shop/owner

**Comment by pxpm** [comment]
Karan wasn't able to give me the reproduction details.
