### ISSUE TITLE
500 error with message No filter view named "range.blade.php" was found.

### ISSUE THREAD

**Issue by rudolphp** [Laravel-Backpack/Demo#67]
# Bug report

### What I did:
installed demo and visited /admin/monster

### What I expected to happen:
show the listing of monster entity

### What happened:
Got 500 error with message No filter view named "range.blade.php" was found. 

### What I've already tried to fix it:
Tried to search for blade range.blade.php

### Backpack, Laravel, PHP, DB version:
Backpack is latest, Laravel is 5.6, PHP 7.2 and DB is MySQL 5.6

**Comment by tabacitu** [comment]
Thank you @rudolphp . I believe we've fixed this in the latest Backpack/Demo. Right?

Thanks, cheers!

**Comment by rudolphp** [comment]
Yes it is fixed. I used the response in this ticket https://github.com/Laravel-Backpack/Demo/issues/64

Thank you.
