### ISSUE TITLE
[Bug] Replace ENUM with with select_from_array

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/demo#68]
Since ENUM doesn't work in Postgres and other DBMSs, we should:
- change the migration to use VARCHAR instead of ENUM for that column
- use the ```select_from_array``` field type instead, which works on all DBMs

Would prevent the demo from seeming "broken" for people who try it on PosgreSQL, SQLite, SQLServer, etc.

**Comment by promatik** [comment]
Fixed with #594.
