### ISSUE TITLE
ERROR 403 Forbidden. This action is unauthorized.

### ISSUE THREAD

**Issue by elivnjak** [Laravel-Backpack/Demo#71]
Hi,

I have done a fresh install of the latest version, no modifications done.

The CRUD seems to work for all the models apart from the User, Roles and permissions.

Any time i try to edit or add a new user, role or permission I get taken to a "ERROR 403 Forbidden. This action is unauthorized." page.

I did a bit of searching through the code and have found the authorize method is whats causing it. For example in PermissionCrudRequest the method \Auth::check(); returns false. I'm not sure why this is exactly.

Laravel 5.6.39
Using PHP 7.2.1
MySql 5.7.23

Any idea why I'm getting this issue?

Thanks

**Comment by tabacitu** [comment]
Hi @elivnjak ,

Did you solve this with a ```composer update```. What worked for you?

Thanks!

**Comment by johnpuddephatt** [comment]
I think as with #72 it's an old version of permission manager that's the problem – composer.json has ^2.1 but latest release is 3.12.6. Any reason for not bumping PermissionManager up to 3.x?

**Comment by tabacitu** [comment]
I think you're totally right, thank you @johnpuddephatt . That must be the issue. I've bumped PermissionManager requirement to 3.x .

Thanks, cheers!

**Comment by tabacitu** [comment]
@elivnjak - a new installation of the demo should work for you now. Thanks for reporting the issue!

**Comment by Bliss911** [comment]
I am getting this error. Can some body help me out. I am running my db, backend and frontend on docker-compose (docker-containers). When I use laravel's Request class, it works fine. But when I import and Type hint a Form Request class I get a 403, Action is Unauthorized in postman. Help please!

**Comment by pxpm** [comment]
@Bliss911 what version of PermissionManager do you have installed ?

**Comment by Bliss911** [comment]
@pxpm my bad. I wasn't working on my PermissionManager Project.
