### ISSUE TITLE
Rbac tables spatie are missing

### ISSUE THREAD

**Issue by robov** [Laravel-Backpack/Demo#73]
![image](https://user-images.githubusercontent.com/8173436/49824827-41b93500-fd83-11e8-9cdc-09053f946da5.png)

**Comment by tabacitu** [comment]
Hi @robov ,

Thanks for the bug report. You're right - looks like we were using a new version of spatie/laravel-permission, when our package PermissionManager only supported an old one.

I've just pushed [a big update to PermissionManager](https://github.com/Laravel-Backpack/PermissionManager/blob/master/CHANGELOG.md#400---2018-12-12) (4.0.0), which supports the latest spatie/laravel-permission. I've also fixed this Demo, to use the latest, and not throw that error. A new install should work fine for you.

Thanks.
Cheers!
