### ISSUE TITLE
Demo - Product Model - Language selector editor doesnt show up

### ISSUE THREAD

**Issue by kpapag** [Laravel-Backpack/Demo#74]
Hello all,

First of all, i want to congratulate the team and community responsible for this excellent software, it gives a serious headstart to any project that someone might develop. Thank you guys.

I am toying around @localhost with a fresh install of backpack demo in laravel 5.8. My specs are:

PHP 7.3.1
MySQL 5.7.24
Apache 2.4.37

Everything seems to run smoothly except i cant trigger the language selector below edit in Product Model. I am attaching a screenshot. HTML seems to be loading the languages, im guessing its some css or js issue. Thank you in advance.

![Screenshot_1](https://user-images.githubusercontent.com/12574598/57034839-43639680-6c59-11e9-8b5a-8c06933a80ce.png)

**Comment by tabacitu** [comment]
Hi @kpapag ,

You're right, thank you. Indeed it's a CSS issue, it has been fixed quite some time ago in Backpack but I see the demo does NOT have the latest CSS and JS. I've now pushed a fix, where I re-published the CSS and JS.

For your own project, you can manually:
1. Delete the ```public/vendor/backpack``` folder.
2. Re-publish the Base and Crud assets (CSS and JS) using ```php artisan backpack:base:install``` and ```php artisan backpack:crud:install```

Thanks for bringing up the issue.
Cheers!
