### ISSUE TITLE
where is the controllers and routes defined ?

### ISSUE THREAD

**Issue by amanullah-1** [Laravel-Backpack/Demo#8]
Hi I just installed the demo with laravel 5.3 and checking the dashboard as it is supposed to be.
But I am wonder that there is no controller is defined for any module like admin dashboard and/or for any sub module like menu , article etc. also there is no routes definition for the views and controllers.

Can anyone please guide how I can start developing?

Thank in advance
Md Aman Ullah

**Comment by OwenMelbz** [comment]
The demo uses the prebuilt CRUDS which are packages on their own, so they'll be will be within a 3rd party vendor folder.

You'll need to create your own admin modules via the method described here -> https://laravel-backpack.readme.io/docs/crud-example

**Comment by amanullah-1** [comment]
thanks a lot ... :)

**Comment by naveenyagati** [comment]
Hi I just installed the demo with laravel 5.3 and while migrating encountered the follwing errors
 
[Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "categories" add column "slug" varchar not null)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL

  [PDOException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
