### ISSUE TITLE
Menu --> ERROR 404 Page not found

### ISSUE THREAD

**Issue by avedmigen** [Laravel-Backpack/Demo#80]
# Bug report
 ### What happened:
Demo ver. -->Admin area --> Menu --> ERROR 404 Page not found
http://127.0.0.1:8000/admin/menu-item
### Backpack, Laravel,  
Fresh today's installation.

fix it plz.

**Comment by anjoalre** [comment]
Yes this is throwing 404 out of the box.

**Comment by tabacitu** [comment]
Thank you guys! There was a problem in MenuCRUD indeed, it's since been fixed in MenuCRUD 2.0.1. Let me know if you still encounter problems.

Cheers!
