### ISSUE TITLE
Getting some migration errors

### ISSUE THREAD

**Issue by naveenyagati** [Laravel-Backpack/Demo#9]
Hi I just installed the demo with laravel 5.3 and while migrating encountered the follwing errors

[Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "categories" add column "slug" varchar not null)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL

  [PDOException]
  SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL

**Comment by tabacitu** [comment]
That's weird, I didn't get any of that. What are you using? MySQL? PosgreSQL? SQLite? SQLServer?

**Comment by naveenyagati** [comment]
Im using SQlite

**Comment by tabacitu** [comment]
SQLite is not officially supported by Backpack (only MySQL) but there are very very few known incompatibility issues with SQLite, PosgreSQL, etc. This was not one of them :-)

If you intend on using it with SQLite, i really appreciate any fixes or pull requests you could submit to make it work for everyone using SQLite.

Thanks, cheers!

**Comment by dmitrybalabus** [comment]
I'm using MySQL and the last version of XAMPP server, and have same error while run this command:
`php artisan migrate`

**Comment by lloy0076** [comment]
Can you upload your migrations?

**Comment by tabacitu** [comment]
Thanks for sharing your experience @dmitrybalabus !
